### ISSUE TITLE
problem with x-show on this release 3.3.4

### ISSUE THREAD

**Issue by ravenshill** [alpinejs/alpine#2080]
### Discussed in https://github.com/alpinejs/alpine/discussions/2079

<div type='discussions-op-text'>

<sup>Originally posted by **ravenshill** September 16, 2021</sup>
x-show is not working on 3.3.4, is ok on 3.3.3 . It shows up on very simple code.  see some snippets from my code below. Have not included the full source here.  I noticed this update included some code changes for x-show.   

 <button @click="isOpen=!isOpen; console.log('Popular clicked');  console.log(isOpen);" type="button" 
...
<div x-show="isOpen" x-cloak @click.outside="isOpen = false"
..</div>

**Comment by svirmasalo** [comment]
I can confirm this problem. 

Very basic implementation of x-show caused a following error:

`Uncaught (in promise) TypeError: e is not a function`

The code I used:

```
<div x-data="{megamenuOpen: false}" >
  <nav>
    <!-- ... -->
    <button @click="megamenuOpen = !megamenuOpen" >Open dropdown</button>
  </nav>
  <ul x-show="megamenuOpen" @click.away="megamenuOpen = false">
    <!-- ... -->
  </ul>
</div>
```

Forcing the 3.3.3 version form CDN was my solution:

`https://unpkg.com/alpinejs@3.3.3/dist/cdn.min.js`

**Comment by Tim-Wils** [comment]
While testing this (I used .outside from the docs) I discovered 3.3.4 is not the problem for me in this one, but the x-on:click,outside is fired directly after the click on the toggle so that the var is toggled back off.

@SimoTod What do you think? Is there an easy solution for not firing .outside in this particular situation?

Slimmed down example: 
https://jsfiddle.net/9a7dLrfs/

**Comment by SimoTod** [comment]
> While testing this (I used .outside from the docs) I discovered 3.3.4 is not the problem for me in this one, but the x-on:click,outside is fired directly after the click on the toggle so that the var is toggled back off.
> 
> @SimoTod What do you think? Is there an easy solution for not firing .outside in this particular situation?
> 
> Slimmed down example:
> https://jsfiddle.net/9a7dLrfs/

Your script worked in 3.3.3 so I think the update is relevant. However, you can also apply the `stop` modifier to your button
`<button x-on:click.stop="open=!open; console.log('toggle')">Toggle</button>`

**Comment by steveallinson** [comment]
Can confirm the issue here too. x-show not working correctly on a number of my components when using 3.3.4. Reverting to 3.3.3 fixes the issue.

**Comment by zawilliams** [comment]
Can confirm the same issue with x-show is not working correctly using 3.3.4 as well.
