### ISSUE TITLE
@alpinejs/persist: "d is not a function" error in recent @3.x.x release (works fine on 3.15.0)

### ISSUE THREAD

**Issue by Emirix** [alpinejs/alpine#4874]
### Alpine.js version

v3.14.1

### Browser and operating system

Chrome on Windows 11

### Describe the issue you're experiencing

Using `@alpinejs/persist` via CDN with the `@3.x.x` dynamic version tag started throwing a `d is not a function` JS runtime error recently. Pinning the version back to `3.15.0` fixes the issue completely. (My Alpine version is v3.14.1)

### Steps to Reproduce
1. Load Alpine Persist plugin via CDN (`@3.x.x` tag) prior to Alpine core:
   ```html
   <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>
   <script> /* I load  alpine v3.14.1 on here */ </script>

### Screenshots/screen recordings

_No response_

### How do you expect it to work?

Should work fine

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be removed if I haven't met the criteria above.

**Comment by calebporzio** [comment]
Thanks for reporting this. The compatibility fix shipped in Alpine/Persist 3.16.1, so `@alpinejs/persist@3.x.x` should now work again with Alpine 3.14.1.

https://github.com/alpinejs/alpine/releases/tag/v3.16.1
